INSERT INTO public.countries (name,code) VALUES ('Afghanistan',93);
INSERT INTO public.countries (name,code) VALUES ('Albania',355);
INSERT INTO public.countries (name,code) VALUES ('Algeria',213);
INSERT INTO public.countries (name,code) VALUES ('American Samoa',1);
INSERT INTO public.countries (name,code) VALUES ('Andorra',376);
INSERT INTO public.countries (name,code) VALUES ('Angola',244);
INSERT INTO public.countries (name,code) VALUES ('Anguilla',1);
INSERT INTO public.countries (name,code) VALUES ('Antigua and Barbuda',1);
INSERT INTO public.countries (name,code) VALUES ('Argentina',54);
INSERT INTO public.countries (name,code) VALUES ('Armenia',374);
INSERT INTO public.countries (name,code) VALUES ('Aruba',297);
INSERT INTO public.countries (name,code) VALUES ('Ascension',247);
INSERT INTO public.countries (name,code) VALUES ('Australia',61);
INSERT INTO public.countries (name,code) VALUES ('Austria',43);
INSERT INTO public.countries (name,code) VALUES ('Azerbaijan',994);
INSERT INTO public.countries (name,code) VALUES ('Bahamas',1);
INSERT INTO public.countries (name,code) VALUES ('Bahrain',973);
INSERT INTO public.countries (name,code) VALUES ('Bangladesh',880);
INSERT INTO public.countries (name,code) VALUES ('Barbados',1);
INSERT INTO public.countries (name,code) VALUES ('Belarus',375);
INSERT INTO public.countries (name,code) VALUES ('Belgium',32);
INSERT INTO public.countries (name,code) VALUES ('Belize',501);
INSERT INTO public.countries (name,code) VALUES ('Benin',229);
INSERT INTO public.countries (name,code) VALUES ('Bermuda',1);
INSERT INTO public.countries (name,code) VALUES ('Bhutan',975);
INSERT INTO public.countries (name,code) VALUES ('Bolivia',591);
INSERT INTO public.countries (name,code) VALUES ('Bosnia and Herzegovina',387);
INSERT INTO public.countries (name,code) VALUES ('Botswana',267);
INSERT INTO public.countries (name,code) VALUES ('Brazil',55);
INSERT INTO public.countries (name,code) VALUES ('British Virgin Islands',1);
INSERT INTO public.countries (name,code) VALUES ('Brunei',673);
INSERT INTO public.countries (name,code) VALUES ('Bulgaria',359);
INSERT INTO public.countries (name,code) VALUES ('Burkina Faso',226);
INSERT INTO public.countries (name,code) VALUES ('Burundi',257);
INSERT INTO public.countries (name,code) VALUES ('Cambodia',855);
INSERT INTO public.countries (name,code) VALUES ('Cameroon',237);
INSERT INTO public.countries (name,code) VALUES ('Canada',1);
INSERT INTO public.countries (name,code) VALUES ('Cape Verde',238);
INSERT INTO public.countries (name,code) VALUES ('Cayman Islands',1);
INSERT INTO public.countries (name,code) VALUES ('Central African Rep.',236);
INSERT INTO public.countries (name,code) VALUES ('Chad',235);
INSERT INTO public.countries (name,code) VALUES ('Chile',56);
INSERT INTO public.countries (name,code) VALUES ('China',86);
INSERT INTO public.countries (name,code) VALUES ('Colombia',57);
INSERT INTO public.countries (name,code) VALUES ('Comoros',269);
INSERT INTO public.countries (name,code) VALUES ('Congo',242);
INSERT INTO public.countries (name,code) VALUES ('Congo (Kinshasa)',243);
INSERT INTO public.countries (name,code) VALUES ('Cook Islands',682);
INSERT INTO public.countries (name,code) VALUES ('Costa Rica',506);
INSERT INTO public.countries (name,code) VALUES ('Croatia',385);
INSERT INTO public.countries (name,code) VALUES ('Cuba',53);
INSERT INTO public.countries (name,code) VALUES ('Curacao',599);
INSERT INTO public.countries (name,code) VALUES ('Cyprus',357);
INSERT INTO public.countries (name,code) VALUES ('Czech Republic',420);
INSERT INTO public.countries (name,code) VALUES ('Denmark',45);
INSERT INTO public.countries (name,code) VALUES ('Diego Garcia',246);
INSERT INTO public.countries (name,code) VALUES ('Djibouti',253);
INSERT INTO public.countries (name,code) VALUES ('Dominica',1);
INSERT INTO public.countries (name,code) VALUES ('Dominican Republic',1);
INSERT INTO public.countries (name,code) VALUES ('East Timor',670);
INSERT INTO public.countries (name,code) VALUES ('Ecuador',593);
INSERT INTO public.countries (name,code) VALUES ('Egypt',20);
INSERT INTO public.countries (name,code) VALUES ('El Salvador',503);
INSERT INTO public.countries (name,code) VALUES ('Equatorial Guinea',240);
INSERT INTO public.countries (name,code) VALUES ('Eritrea',291);
INSERT INTO public.countries (name,code) VALUES ('Estonia',372);
INSERT INTO public.countries (name,code) VALUES ('Ethiopia',251);
INSERT INTO public.countries (name,code) VALUES ('Falkland Islands',500);
INSERT INTO public.countries (name,code) VALUES ('Faroe Islands',298);
INSERT INTO public.countries (name,code) VALUES ('Fiji',679);
INSERT INTO public.countries (name,code) VALUES ('Finland',358);
INSERT INTO public.countries (name,code) VALUES ('France',33);
INSERT INTO public.countries (name,code) VALUES ('French Guiana',594);
INSERT INTO public.countries (name,code) VALUES ('French Polynesia',689);
INSERT INTO public.countries (name,code) VALUES ('Gabon',241);
INSERT INTO public.countries (name,code) VALUES ('Gambia',220);
INSERT INTO public.countries (name,code) VALUES ('Georgia',995);
INSERT INTO public.countries (name,code) VALUES ('Germany',49);
INSERT INTO public.countries (name,code) VALUES ('Ghana',233);
INSERT INTO public.countries (name,code) VALUES ('Gibraltar',350);
INSERT INTO public.countries (name,code) VALUES ('Greece',30);
INSERT INTO public.countries (name,code) VALUES ('Greenland',299);
INSERT INTO public.countries (name,code) VALUES ('Grenada',1);
INSERT INTO public.countries (name,code) VALUES ('Guadeloupe',590);
INSERT INTO public.countries (name,code) VALUES ('Guam',1);
INSERT INTO public.countries (name,code) VALUES ('Guatemala',502);
INSERT INTO public.countries (name,code) VALUES ('Guinea',224);
INSERT INTO public.countries (name,code) VALUES ('Guinea-Bissau',245);
INSERT INTO public.countries (name,code) VALUES ('Guyana',592);
INSERT INTO public.countries (name,code) VALUES ('Haiti',509);
INSERT INTO public.countries (name,code) VALUES ('Honduras',504);
INSERT INTO public.countries (name,code) VALUES ('Hong Kong',852);
INSERT INTO public.countries (name,code) VALUES ('Hungary',36);
INSERT INTO public.countries (name,code) VALUES ('Iceland',354);
INSERT INTO public.countries (name,code) VALUES ('India',91);
INSERT INTO public.countries (name,code) VALUES ('Indonesia',62);
INSERT INTO public.countries (name,code) VALUES ('Iran',98);
INSERT INTO public.countries (name,code) VALUES ('Iraq',964);
INSERT INTO public.countries (name,code) VALUES ('Ireland',353);
INSERT INTO public.countries (name,code) VALUES ('Israel',972);
INSERT INTO public.countries (name,code) VALUES ('Italy',39);
INSERT INTO public.countries (name,code) VALUES ('Ivory Coast',225);
INSERT INTO public.countries (name,code) VALUES ('Jamaica',1);
INSERT INTO public.countries (name,code) VALUES ('Japan',81);
INSERT INTO public.countries (name,code) VALUES ('Jordan',962);
INSERT INTO public.countries (name,code) VALUES ('Kazakhstan',7);
INSERT INTO public.countries (name,code) VALUES ('Kenya',254);
INSERT INTO public.countries (name,code) VALUES ('Kiribati',686);
INSERT INTO public.countries (name,code) VALUES ('Kosovo',383);
INSERT INTO public.countries (name,code) VALUES ('Kuwait',965);
INSERT INTO public.countries (name,code) VALUES ('Kyrgyzstan',996);
INSERT INTO public.countries (name,code) VALUES ('Laos',856);
INSERT INTO public.countries (name,code) VALUES ('Latvia',371);
INSERT INTO public.countries (name,code) VALUES ('Lebanon',961);
INSERT INTO public.countries (name,code) VALUES ('Lesotho',266);
INSERT INTO public.countries (name,code) VALUES ('Liberia',231);
INSERT INTO public.countries (name,code) VALUES ('Libya',218);
INSERT INTO public.countries (name,code) VALUES ('Liechtenstein',423);
INSERT INTO public.countries (name,code) VALUES ('Lithuania',370);
INSERT INTO public.countries (name,code) VALUES ('Luxembourg',352);
INSERT INTO public.countries (name,code) VALUES ('Macau',853);
INSERT INTO public.countries (name,code) VALUES ('Madagascar',261);
INSERT INTO public.countries (name,code) VALUES ('Malawi',265);
INSERT INTO public.countries (name,code) VALUES ('Malaysia',60);
INSERT INTO public.countries (name,code) VALUES ('Maldives',960);
INSERT INTO public.countries (name,code) VALUES ('Mali',223);
INSERT INTO public.countries (name,code) VALUES ('Malta',356);
INSERT INTO public.countries (name,code) VALUES ('Marshall Islands',692);
INSERT INTO public.countries (name,code) VALUES ('Martinique',596);
INSERT INTO public.countries (name,code) VALUES ('Mauritania',222);
INSERT INTO public.countries (name,code) VALUES ('Mauritius',230);
INSERT INTO public.countries (name,code) VALUES ('Mayotte',262);
INSERT INTO public.countries (name,code) VALUES ('Mexico',52);
INSERT INTO public.countries (name,code) VALUES ('Micronesia',691);
INSERT INTO public.countries (name,code) VALUES ('Moldova',373);
INSERT INTO public.countries (name,code) VALUES ('Monaco',377);
INSERT INTO public.countries (name,code) VALUES ('Mongolia',976);
INSERT INTO public.countries (name,code) VALUES ('Montenegro',382);
INSERT INTO public.countries (name,code) VALUES ('Montserrat',1);
INSERT INTO public.countries (name,code) VALUES ('Morocco',212);
INSERT INTO public.countries (name,code) VALUES ('Mozambique',258);
INSERT INTO public.countries (name,code) VALUES ('Myanmar',95);
INSERT INTO public.countries (name,code) VALUES ('Namibia',264);
INSERT INTO public.countries (name,code) VALUES ('Nauru',674);
INSERT INTO public.countries (name,code) VALUES ('Nepal',977);
INSERT INTO public.countries (name,code) VALUES ('Netherlands',31);
INSERT INTO public.countries (name,code) VALUES ('Netherlands Antilles',599);
INSERT INTO public.countries (name,code) VALUES ('New Caledonia',687);
INSERT INTO public.countries (name,code) VALUES ('New Zealand',64);
INSERT INTO public.countries (name,code) VALUES ('Nicaragua',505);
INSERT INTO public.countries (name,code) VALUES ('Niger',227);
INSERT INTO public.countries (name,code) VALUES ('Nigeria',234);
INSERT INTO public.countries (name,code) VALUES ('Niue',683);
INSERT INTO public.countries (name,code) VALUES ('Norfolk Island',672);
INSERT INTO public.countries (name,code) VALUES ('North Korea',850);
INSERT INTO public.countries (name,code) VALUES ('North Macedonia',389);
INSERT INTO public.countries (name,code) VALUES ('Northern Mariana',1);
INSERT INTO public.countries (name,code) VALUES ('Norway',47);
INSERT INTO public.countries (name,code) VALUES ('Oman',968);
INSERT INTO public.countries (name,code) VALUES ('Pakistan',92);
INSERT INTO public.countries (name,code) VALUES ('Palau',680);
INSERT INTO public.countries (name,code) VALUES ('Palestine',970);
INSERT INTO public.countries (name,code) VALUES ('Panama',507);
INSERT INTO public.countries (name,code) VALUES ('Papua New Guinea',675);
INSERT INTO public.countries (name,code) VALUES ('Paraguay',595);
INSERT INTO public.countries (name,code) VALUES ('Peru',51);
INSERT INTO public.countries (name,code) VALUES ('Philippines',63);
INSERT INTO public.countries (name,code) VALUES ('Poland',48);
INSERT INTO public.countries (name,code) VALUES ('Portugal',351);
INSERT INTO public.countries (name,code) VALUES ('Puerto Rico',1);
INSERT INTO public.countries (name,code) VALUES ('Qatar',974);
INSERT INTO public.countries (name,code) VALUES ('Reunion',262);
INSERT INTO public.countries (name,code) VALUES ('Romania',40);
INSERT INTO public.countries (name,code) VALUES ('Russian Federation',7);
INSERT INTO public.countries (name,code) VALUES ('Rwanda',250);
INSERT INTO public.countries (name,code) VALUES ('Saint Helena',290);
INSERT INTO public.countries (name,code) VALUES ('Saint Kitts and Nevis',1);
INSERT INTO public.countries (name,code) VALUES ('Saint Lucia',1);
INSERT INTO public.countries (name,code) VALUES ('Saint Barthelemy',590);
INSERT INTO public.countries (name,code) VALUES ('Saint Martin',590);
INSERT INTO public.countries (name,code) VALUES ('Saint Pierre and Miquelon',508);
INSERT INTO public.countries (name,code) VALUES ('Saint Vincent',1);
INSERT INTO public.countries (name,code) VALUES ('Samoa',685);
INSERT INTO public.countries (name,code) VALUES ('San Marino',378);
INSERT INTO public.countries (name,code) VALUES ('Sao Tome and Principe',239);
INSERT INTO public.countries (name,code) VALUES ('Saudi Arabia',966);
INSERT INTO public.countries (name,code) VALUES ('Senegal',221);
INSERT INTO public.countries (name,code) VALUES ('Serbia',381);
INSERT INTO public.countries (name,code) VALUES ('Seychelles',248);
INSERT INTO public.countries (name,code) VALUES ('Sierra Leone',232);
INSERT INTO public.countries (name,code) VALUES ('Singapore',65);
INSERT INTO public.countries (name,code) VALUES ('Sint Maarten',1);
INSERT INTO public.countries (name,code) VALUES ('Slovakia',421);
INSERT INTO public.countries (name,code) VALUES ('Slovenia',386);
INSERT INTO public.countries (name,code) VALUES ('Solomon Islands',677);
INSERT INTO public.countries (name,code) VALUES ('Somalia',252);
INSERT INTO public.countries (name,code) VALUES ('South Africa',27);
INSERT INTO public.countries (name,code) VALUES ('South Korea',82);
INSERT INTO public.countries (name,code) VALUES ('South Sudan',211);
INSERT INTO public.countries (name,code) VALUES ('Spain',34);
INSERT INTO public.countries (name,code) VALUES ('Sri Lanka',94);
INSERT INTO public.countries (name,code) VALUES ('Sudan',249);
INSERT INTO public.countries (name,code) VALUES ('Suriname',597);
INSERT INTO public.countries (name,code) VALUES ('Swaziland',268);
INSERT INTO public.countries (name,code) VALUES ('Sweden',46);
INSERT INTO public.countries (name,code) VALUES ('Switzerland',41);
INSERT INTO public.countries (name,code) VALUES ('Syria',963);
INSERT INTO public.countries (name,code) VALUES ('Taiwan',886);
INSERT INTO public.countries (name,code) VALUES ('Tajikistan',992);
INSERT INTO public.countries (name,code) VALUES ('Tanzania',255);
INSERT INTO public.countries (name,code) VALUES ('Thailand',66);
INSERT INTO public.countries (name,code) VALUES ('Togo',228);
INSERT INTO public.countries (name,code) VALUES ('Tokelau',690);
INSERT INTO public.countries (name,code) VALUES ('Tonga',676);
INSERT INTO public.countries (name,code) VALUES ('Trinidad and Tobago',1);
INSERT INTO public.countries (name,code) VALUES ('Tunisia',216);
INSERT INTO public.countries (name,code) VALUES ('Turkey',90);
INSERT INTO public.countries (name,code) VALUES ('Turkmenistan',993);
INSERT INTO public.countries (name,code) VALUES ('Turks and Caicos',1);
INSERT INTO public.countries (name,code) VALUES ('Tuvalu',688);
INSERT INTO public.countries (name,code) VALUES ('Uganda',256);
INSERT INTO public.countries (name,code) VALUES ('Ukraine',380);
INSERT INTO public.countries (name,code) VALUES ('United Arab Emirates',971);
INSERT INTO public.countries (name,code) VALUES ('United Kingdom',44);
INSERT INTO public.countries (name,code) VALUES ('United States',1);
INSERT INTO public.countries (name,code) VALUES ('US Virgin Islands',1);
INSERT INTO public.countries (name,code) VALUES ('Uruguay',598);
INSERT INTO public.countries (name,code) VALUES ('Uzbekistan',998);
INSERT INTO public.countries (name,code) VALUES ('Vanuatu',678);
INSERT INTO public.countries (name,code) VALUES ('Venezuela',58);
INSERT INTO public.countries (name,code) VALUES ('Vietnam',84);
INSERT INTO public.countries (name,code) VALUES ('Wallis and Futuna',681);
INSERT INTO public.countries (name,code) VALUES ('Yemen',967);
INSERT INTO public.countries (name,code) VALUES ('Zambia',260);
INSERT INTO public.countries (name,code) VALUES ('Zimbabwe',263);